#!/bin/bash
# Turn the raw inventory into the first catalog draft.
#
#   bash tools/inventory/collect.sh > catalog/inventory.tsv
#   bash tools/inventory/report.sh catalog/inventory.tsv > catalog/INVENTORY.md
#
# Output goes to catalog/, which is gitignored. It names every project and every
# credential on the machine, and this repo is MIT with a public remote. That is
# reconnaissance data even though it holds no values. Regenerate it any time;
# the tools are the durable part, not the report.

set -uo pipefail

TSV="${1:?usage: report.sh <inventory.tsv>}"
AWKDIR="$(cd "$(dirname "$0")" && pwd)"

CLASSIFIED=$(awk -f "$AWKDIR/classify.awk" "$TSV")

total_rows=$(echo "$CLASSIFIED" | wc -l | tr -d ' ')
total_files=$(cut -f1,2 "$TSV" | sort -u | wc -l | tr -d ' ')
total_projects=$(cut -f1 "$TSV" | sort -u | wc -l | tr -d ' ')
distinct=$(cut -f3 "$TSV" | sort -u | wc -l | tr -d ' ')

# Real files only for the numbers that drive vault sizing. Example and template
# files document names but hold nothing.
REAL=$(echo "$CLASSIFIED" | awk -F'\t' '$6=="real"')
real_distinct=$(echo "$REAL" | cut -f3 | sort -u | wc -l | tr -d ' ')
real_secrets=$(echo "$REAL" | awk -F'\t' '$7=="secret"' | cut -f3 | sort -u | wc -l | tr -d ' ')
real_public=$(echo "$REAL" | awk -F'\t' '$7=="public"' | cut -f3 | sort -u | wc -l | tr -d ' ')
real_const=$(echo "$REAL" | awk -F'\t' '$7=="constant"' | cut -f3 | sort -u | wc -l | tr -d ' ')
real_review=$(echo "$REAL" | awk -F'\t' '$7=="review"' | cut -f3 | sort -u | wc -l | tr -d ' ')

cat <<HEADER
# Env inventory

Generated by \`tools/inventory/collect.sh\` and \`tools/inventory/report.sh\`.
Contains variable **names** only. No value, and no character of any value, is
read or written by either tool.

**This file is gitignored on purpose.** It names every project and every
credential on this machine. That is useful to the founder and useful to an
attacker, and this repo is MIT with a public remote.

## Headline

| | |
|---|---|
| Projects with env files | $total_projects |
| Env files | $total_files |
| Variable definitions | $total_rows |
| Distinct names | $distinct |
| Distinct names in real (non-example) files | $real_distinct |

### What actually has to go in the vault

| Classification | Distinct names | Meaning |
|---|---|---|
| secret | $real_secrets | Real credentials. These are the vault. |
| review | $real_review | Ambiguous. Needs a human call. |
| constant | $real_const | Decided values. Belong in source, not in a dashboard row. |
| public | $real_public | Compiled into a browser bundle. Cannot be secret by construction. |

The founder's own rule says a value is not an environment variable until it has
to be, and the findmyhooks precedent took 46 variables down to 24 real secrets.
The same shape holds here: of $real_distinct distinct names in real env files,
$real_secrets are credentials.

HEADER

echo "## Shared across projects"
echo
echo "The redundancy problem, measured. These names appear in more than one project,"
echo "so rotating one of them today means editing that many files. This is the list"
echo "that one-key-per-provider collapses."
echo
echo "| Name | Projects | Classification |"
echo "|---|---|---|"
echo "$REAL" | awk -F'\t' '{key=$3"\t"$7; if (!seen[$3"\t"$1]++) count[key]++} END {for (k in count) if (count[k] > 1) print count[k]"\t"k}' \
  | sort -rn -k1 | head -40 \
  | awk -F'\t' '{printf "| `%s` | %s | %s |\n", $2, $1, $3}'

echo
echo "## Providers"
echo
echo "Grouped by the provider prefix in the name. This is the shape of the vault:"
echo "one entry per provider, not one per project."
echo
echo "| Provider | Distinct names | Projects touching it |"
echo "|---|---|---|"
echo "$REAL" | awk -F'\t' '
{
  n = toupper($3)
  p = ""
  split("OPENROUTER OPENAI ANTHROPIC CLAUDE FAL REPLICATE STRIPE RESEND SENDGRID POSTMARK SUPABASE AWS S3 GOOGLE GEMINI GITHUB SLACK DISCORD TWILIO CLOUDFLARE VERCEL REDIS POSTGRES DATABASE ELEVENLABS DEEPGRAM ASSEMBLYAI RUNPOD TAILSCALE COOLIFY SENTRY POSTHOG MIXPANEL", provs, " ")
  for (i in provs) if (index(n, provs[i]) == 1 || index(n, "_" provs[i] "_") > 0) { p = provs[i]; break }
  if (p == "") next
  if (!seenname[p"\t"$3]++) names[p]++
  if (!seenproj[p"\t"$1]++) projs[p]++
}
END { for (k in names) print names[k]"\t"k"\t"projs[k] }' \
  | sort -rn -k1 | head -25 \
  | awk -F'\t' '{printf "| %s | %s | %s |\n", $2, $1, $3}'

echo
echo "## Candidate vault entries"
echo
echo "Secrets that appear in two or more projects. Each of these is one vault entry"
echo "replacing N copies, and each is a rotation that currently means editing N files."
echo
echo "| Name | Projects | Value shape seen |"
echo "|---|---|---|"
echo "$REAL" | awk -F'\t' '$7=="secret" {
  if (!seen[$3"\t"$1]++) count[$3]++
  shape[$3] = $5
} END { for (k in count) if (count[k] > 1) print count[k]"\t"k"\t"shape[k] }' \
  | sort -rn -k1 | head -30 \
  | awk -F'\t' '{printf "| `%s` | %s | %s |\n", $2, $1, $3}'

echo
echo "## Needs a human call"
echo
echo "Classified \`review\`: the name does not clearly say whether it is a credential."
echo "Nothing should be built around these until they are sorted."
echo
echo "$REAL" | awk -F'\t' '$7=="review" {print $3}' | sort -u | head -60 | awk '{printf "- `%s`\n", $1}'

echo
echo "## Retire from the environment entirely"
echo
echo "Classified \`constant\` or \`public\`. Per the founder's rule these are decided"
echo "values, not deployment inputs, and every one of them is a dashboard row that can"
echo "be missing, blank, or wrong. They do not belong in the vault either."
echo
printf 'Distinct names in this category: %s constant, %s public.\n' "$real_const" "$real_public"
